# lightning.pytorch==2.0.0
seed_everything: 42
trainer:
  logger: 
    class_path: lightning.pytorch.loggers.csv_logs.CSVLogger
    init_args:
      save_dir: experiments
      name: "lenet_cifar10"
  callbacks: 
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_last: true
        monitor: val_loss
  max_epochs: 5
model:
  class_path: image_classification.models.modules.LeNetModule
  init_args:
    num_classes: 10
    lr: 0.001
data:
  class_path: image_classification.datasets.modules.CIFAR10Module
  init_args:
    data_dir: data
    batch_size: 32
    num_workers: 4
    val_split:
    - 0.8
    - 0.2